export enum Urls {
  MATCHES = '/matches',
  // MATCHES = '/tournaments/world-cup/editions/qatar-2022/matches',
  MATCHES_ID = '/matches',
  MATCHES_LIVE = '/matches/live',
  // MATCHES_LIVE = '/tournaments/world-cup/editions/qatar-2022/matches/live',
  RANKING = '/ranking',
  // RANKING = '/tournaments/world-cup/editions/qatar-2022/ranking',
  TEAMS = '/teams',
  USERS_SUB = '/users/guid/',
  USERS_ALL = '/users',
  USERS_PROFILE = '/users/profile',
  USERS_ACCEPT_RULES = '/users/guid/{guid}/accept-rules',
  USERS_ACCEPT_DATA_PRIVACY = '/users/guid/{guid}/data-privacy',
  USERS_ACCEPT_PREFERENCES = '/users/guid/{guid}/preferences',
  USERS_BONUS_BETS = '/users/guid/{guid}/bonus',
  USERS_CONFIRM_PAYMENT = '/users/guid/{guid}/payment',
  // USERS_RANKING = '/tournaments/world-cup/editions/qatar-2022/ranking/position',
  USERS_RANKING = '/ranking/position',
  USERS_HISTORY = '/ranking/history',
  BETS_CREATE = '/bets',
  BETS_GET_BY_MATCH = '/bets/matches',
  SURVEY_GET = '/surveys',
  SURVEY_PUT = '/surveys',
}
